# Generated by Django 4.0.4 on 2022-06-04 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', verbose_name='Текст:')),
                ('status', models.SmallIntegerField(choices=[(1, 'Активно'), (2, 'Отложено'), (3, 'Выполнено')], default=1, max_length=1)),
                ('important', models.BooleanField(default=False, verbose_name='Важно:')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата:')),
                ('deadline', models.DateTimeField(default='05/06/22 10:57:25', verbose_name='Выполнить до:')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'заметка',
                'verbose_name_plural': 'заметки',
            },
        ),
    ]
