# Generated by Django 4.0.4 on 2022-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(default='05/06/22 10:58:43', verbose_name='Выполнить до:'),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Активно'), (2, 'Отложено'), (3, 'Выполнено')], default=1),
        ),
    ]
